@host = http://localhost:5002/comment


### get all comment
GET {{host}}


### get comment by id
GET {{host}}/b5b94c83-872b-48c1-bbf3-0f7d077923e2


### create comment
POST {{host}}
Content-Type: application/json

{
  "content": "Comment 1",
  "PostId": "635c9d72-c345-4c38-93fa-508e009a0521"
}


### update comment by id
PUT {{host}}/1
Content-Type: application/json

{
  "content": "cont edited"
}


### delete comment by id
DELETE {{host}}/2
