@host = http://localhost:5002/post

# vasanth - ba8e20b1-f588-49d3-b139-a122bf12d895
# raj - 068e5923-c7e1-4208-8fbc-44949f6c3270

### get all post
GET {{host}}


### get post by id
GET {{host}}/635c9d72-c345-4c38-93fa-508e009a0521


### get all posts by userId
GET {{host}}/user/068e5923-c7e1-4208-8fbc-44949f6c3270


### create post
POST {{host}}
Content-Type: application/json

{
  "title": "Post 5",
  "content": "Lorem ipsum dolor sit.",
  "UserId": "7d81f71b-dfd1-4941-8269-f8e6cfed73c5"
}


### update post by id
PUT {{host}}/4
Content-Type: application/json

{
  "title": "Post 4 edited",
  "content": "cont edited"
}


### delete post by id
DELETE {{host}}/2
