@host = http://localhost:5003/user


### get all user
GET {{host}}


### get user by id
GET {{host}}/9b083134-23b8-4ea4-84e3-32ea49835898


### create user
POST {{host}}
Content-Type: application/json

{
  "firstName": "Vasanth",
  "lastName": "Kumar"
}


### update user by id
PUT {{host}}/1
Content-Type: application/json

{
  "firstName": "Raj",
  "lastName": "kumar"
}


### delete user by id
DELETE {{host}}/9b083134-23b8-4ea4-84e3-32ea49835898
